### ISSUE TITLE
Needs moar git

### ISSUE THREAD

**Issue by LexMalta** [annablog/ctrlcv#1]

**Comment by annablog** [comment]
The context for this issue is that while writing the code for the keyboard, I was modifying the file on the board directly. @LexMalta saw this and was horrified, and I replied, "It's fine, I don't need source control, it's just a small app!"

5 minutes later, it wasn't fine. I accidentally created an infinite loop which I ended up copying some other main.py onto the board - losing all my code as a result. Not an issue anymore, because now it's source controlled!
