### ISSUE TITLE
How to paste password?

### ISSUE THREAD

**Issue by LexMalta** [annablog/ctrlcv#2]

**Comment by annablog** [comment]
Context for this issue. Once I got the code working properly, I went to push my changes (due to the solution for this issue https://github.com/annablog/ctrlcv/issues/1 ) which meant I needed my github password which was in my password manager. I copied my password and pushed successfully.

I then went to show off my progress to a friend, and showed him how paste was working. Well, the last thing I had copied was my github password, so I cleverly pasted this to my friend, thus proving that my keyboard code was working as intended!

For some reason, @LexMalta finds this hilarious. I haven't been able to reproduce the humour.

Since I no longer feel the need to show off my keyboard, and I don't think anybody will be as stupid as me, I am closing this as it doesn't apply anymore.
